---
title: "class06"
author: "Daniel Xu"
format: pdf
---
```{r}
grade<-function(arr){
#parses the array to remove NA and changes them to 0
arr[is.na(arr)]<-0
# assign index to the index of the minimum of the arr
index <-which.min(arr)
#create an adjusted arr without the minimum score
adjusted <- arr[-index]

#apply mean function to return the average grade
mean(adjusted)
}

# Example input vectors to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)
# read in the csv
df<-read.csv("https://tinyurl.com/gradeinput",row.names=1)
# apply the function to each row removing the names of the students
grades<-apply(df,1,grade) 
print(grades)
which.max(grades)
```
Q2 The top scoring student is student 18 

```{r}
Assignments<-apply(df,2,sum,na.rm=TRUE) 
print(Assignments)
which.min(Assignments)
```

Q3 based on this analysis homework two was the most difficult 

Q4 
```{r}
mask<-df
mask[is.na(df)]<-0
print(mask)

apply(mask,2,cor, y=grades)
```

Homework 5 has the greatest correlation score 